# Generated by Django 2.2.1 on 2019-06-01 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('badge', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_url', models.URLField()),
                ('one_day', models.PositiveSmallIntegerField(null=True)),
                ('three_day', models.PositiveSmallIntegerField(null=True)),
                ('six_day', models.PositiveSmallIntegerField(null=True)),
                ('one_day_r', models.PositiveSmallIntegerField(null=True)),
                ('three_day_r', models.PositiveSmallIntegerField(null=True)),
                ('six_day_r', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COLOUR', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LAT', models.FloatField()),
                ('LONG', models.FloatField()),
                ('ALT', models.FloatField()),
                ('TS', models.DateTimeField()),
                ('CLS', models.CharField(max_length=20)),
                ('EL', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('LAYERS', models.ManyToManyField(blank=True, to='trips.Layer')),
                ('MARKERS', models.ManyToManyField(blank=True, to='trips.Marker')),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='TRIP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
        ),
        migrations.CreateModel(
            name='LayerPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LAT', models.FloatField()),
                ('LONG', models.FloatField()),
                ('ALT', models.FloatField()),
                ('TS', models.DateTimeField()),
                ('LAYER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Layer')),
            ],
            options={
                'ordering': ['TS'],
            },
        ),
        migrations.AddField(
            model_name='layer',
            name='TRIP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
        ),
    ]
