# Generated by Django 2.2.1 on 2019-06-01 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='description',
            new_name='DESCRIPTION',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='title',
            new_name='TITLE',
        ),
    ]
