# Generated by Django 2.2.1 on 2019-06-03 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20190603_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='TRIP',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='TRIP',
        ),
        migrations.AlterField(
            model_name='layerpoint',
            name='LAYER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POINTS', to='trips.Layer'),
        ),
    ]
